import {
  formatCurrency,
  formatQuantity,
  formatSignedPercentage,
} from '../portfolio/portfolioMath'

const dateFormatter = new Intl.DateTimeFormat('en-US', {
  day: 'numeric',
  month: 'short',
  year: 'numeric',
  timeZone: 'UTC',
})

function formatDate(value) {
  return dateFormatter.format(new Date(`${value}T00:00:00Z`))
}

export default function TradeHistoryTable({ trades }) {
  return (
    <section className="backtest-card backtest-trades-card" aria-labelledby="backtest-trades-title">
      <div className="backtest-card-header">
        <div>
          <p>Executed signals</p>
          <h2 id="backtest-trades-title">Trade History</h2>
          <span>Simulated entries and exits generated by the selected strategy rules.</span>
        </div>
        <strong className="backtest-record-count">{trades.length} trades</strong>
      </div>

      <div className="backtest-table-wrap">
        <table className="backtest-trades-table">
          <caption className="sr-only">Simulated backtest trade history</caption>
          <thead>
            <tr>
              <th scope="col">Date</th>
              <th scope="col">Action</th>
              <th scope="col">Price</th>
              <th scope="col">Quantity</th>
              <th scope="col">Trade Value</th>
              <th scope="col">Return</th>
              <th scope="col">Signal Reason</th>
            </tr>
          </thead>
          <tbody>
            {trades.map((trade) => (
              <tr key={trade.id}>
                <td data-label="Date">{formatDate(trade.date)}</td>
                <td data-label="Action">
                  <span className={`backtest-trade-action is-${trade.action.toLowerCase()}`}>{trade.action}</span>
                </td>
                <td data-label="Price">{formatCurrency(trade.price)}</td>
                <td data-label="Quantity">{formatQuantity(trade.quantity)}</td>
                <td data-label="Trade Value"><strong>{formatCurrency(trade.tradeValue)}</strong></td>
                <td data-label="Return">
                  {trade.returnPercent === null ? (
                    <span className="backtest-return is-neutral">—</span>
                  ) : (
                    <span className={`backtest-return ${trade.returnPercent >= 0 ? 'is-positive' : 'is-negative'}`}>
                      {formatSignedPercentage(trade.returnPercent)}
                    </span>
                  )}
                </td>
                <td data-label="Signal Reason"><span className="backtest-signal-reason">{trade.signalReason}</span></td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </section>
  )
}
