# Generated by Django 6.0.6 on 2026-07-28 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityDailyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.DecimalField(decimal_places=6, max_digits=20)),
                ('high', models.DecimalField(decimal_places=6, max_digits=20)),
                ('low', models.DecimalField(decimal_places=6, max_digits=20)),
                ('close', models.DecimalField(decimal_places=6, max_digits=20)),
                ('volume', models.BigIntegerField(default=0)),
                ('source', models.CharField(default='TWELVE_DATA', max_length=32)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_prices', to='market.security')),
            ],
            options={
                'ordering': ['security', 'date'],
                'indexes': [models.Index(fields=['security', 'date'], name='daily_price_security_date_idx'), models.Index(fields=['security', '-date'], name='daily_price_sec_date_desc_idx')],
                'constraints': [models.UniqueConstraint(fields=('security', 'date'), name='unique_daily_price_security_date')],
            },
        ),
    ]
