# Generated by Django 6.0.6 on 2026-08-02 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_securitydailyprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='country',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='security',
            name='mic_code',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='security',
            name='symbol',
            field=models.CharField(db_index=True, max_length=16),
        ),
        migrations.AddIndex(
            model_name='security',
            index=models.Index(fields=['symbol', 'mic_code'], name='security_symbol_mic_idx'),
        ),
        migrations.AddConstraint(
            model_name='security',
            constraint=models.UniqueConstraint(fields=('symbol', 'mic_code'), name='unique_security_symbol_mic_code'),
        ),
    ]
