# Generated by Django 6.0.6 on 2026-07-18 01:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=16)),
                ('display_name', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', 'symbol'],
                'constraints': [models.UniqueConstraint(fields=('user', 'symbol'), name='unique_watchlist_symbol_per_user'), models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('symbol',), name='unique_watchlist_symbol_for_anonymous')],
            },
        ),
    ]
