# Generated by Django 6.0.6 on 2026-07-20 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='watchlistitem',
            name='unique_watchlist_symbol_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='watchlistitem',
            name='unique_watchlist_symbol_for_anonymous',
        ),
        migrations.DeleteModel(
            name='WatchlistItem',
        ),
    ]
