# Generated by Django 6.0.6 on 2026-08-19 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0003_security_country_security_mic_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentAgentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('success', 'Success')], default='success', max_length=16)),
                ('as_of_date', models.DateField(blank=True, null=True)),
                ('context_version', models.CharField(blank=True, default='', max_length=64)),
                ('analysis_version', models.CharField(blank=True, default='', max_length=64)),
                ('provider', models.CharField(blank=True, default='', max_length=64)),
                ('model', models.CharField(blank=True, default='', max_length=64)),
                ('analysis', models.JSONField(default=dict)),
                ('failure_metadata', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_analyses', to='market.security')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['user', 'security', '-generated_at'], name='agent_analysis_user_sec_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'security'), name='uniq_user_security_latest_agent_analysis')],
            },
        ),
    ]
