# Generated by Django 6.0.6 on 2026-07-22 20:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('DIVIDEND', 'Dividend')], max_length=16)),
                ('quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))])),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('cash_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('transaction_date', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_transactions', to='portfolio.portfolio')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trade_transactions', to='market.security')),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
                'indexes': [models.Index(fields=['portfolio', '-transaction_date'], name='trade_txn_port_date_idx'), models.Index(fields=['security', '-transaction_date'], name='trade_txn_sec_date_idx'), models.Index(fields=['transaction_date'], name='trade_txn_date_idx')],
            },
        ),
    ]
