# Generated by Django 6.0.6 on 2026-07-22 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_tradetransaction'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='txn_portfolio_exec_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='txn_security_exec_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='txn_executed_idx',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
