# Generated by Django 6.0.6 on 2026-08-03 02:24

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models
from django.utils import timezone


def backfill_initial_cash_flows(apps, schema_editor):
    Portfolio = apps.get_model('portfolio', 'Portfolio')
    PortfolioCashFlow = apps.get_model('portfolio', 'PortfolioCashFlow')
    TradeTransaction = apps.get_model('portfolio', 'TradeTransaction')
    db_alias = schema_editor.connection.alias

    for portfolio in Portfolio.objects.using(db_alias).all():
        if PortfolioCashFlow.objects.using(db_alias).filter(
            portfolio_id=portfolio.id,
            flow_type='INITIAL',
        ).exists():
            continue

        initial_cash = portfolio.available_funds or Decimal('0')
        transactions = TradeTransaction.objects.using(db_alias).filter(portfolio_id=portfolio.id)
        for trade_transaction in transactions:
            quantity = trade_transaction.quantity or Decimal('0')
            price = trade_transaction.price or Decimal('0')
            fee = trade_transaction.fee or Decimal('0')
            gross_amount = quantity * price

            if trade_transaction.transaction_type == 'BUY':
                initial_cash += gross_amount + fee
            elif trade_transaction.transaction_type == 'SELL':
                initial_cash -= gross_amount - fee

        PortfolioCashFlow.objects.using(db_alias).create(
            portfolio_id=portfolio.id,
            flow_type='INITIAL',
            amount=initial_cash,
            effective_date=portfolio.created_at or timezone.now(),
            note='Estimated from current remaining liquidity and recorded buy/sell transactions during migration.',
            is_estimated=True,
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_transaction_txn_portfolio_exec_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioCashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_type', models.CharField(choices=[('INITIAL', 'Initial'), ('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('ADJUSTMENT', 'Adjustment')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('effective_date', models.DateTimeField()),
                ('note', models.TextField(blank=True)),
                ('is_estimated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_flows', to='portfolio.portfolio')),
            ],
            options={
                'ordering': ['effective_date', 'id'],
                'indexes': [models.Index(fields=['portfolio', 'effective_date'], name='cash_flow_port_date_idx'), models.Index(fields=['portfolio', 'flow_type'], name='cash_flow_port_type_idx')],
            },
        ),
        migrations.RunPython(backfill_initial_cash_flows, noop_reverse),
    ]
