# Generated by Django 6.0.6 on 2026-08-04 01:50

from decimal import Decimal, ROUND_HALF_UP
from django.db import migrations, models


ZERO = Decimal('0')
MONEY_QUANTIZER = Decimal('0.01')
AVERAGE_COST_QUANTIZER = Decimal('0.0001')


def quantize_money(value):
    return (value or ZERO).quantize(MONEY_QUANTIZER, rounding=ROUND_HALF_UP)


def quantize_average_cost(value):
    return (value or ZERO).quantize(AVERAGE_COST_QUANTIZER, rounding=ROUND_HALF_UP)


def backfill_realized_profit_loss(apps, schema_editor):
    Portfolio = apps.get_model('portfolio', 'Portfolio')
    Holding = apps.get_model('portfolio', 'Holding')
    TradeTransaction = apps.get_model('portfolio', 'TradeTransaction')
    db_alias = schema_editor.connection.alias

    for portfolio_id in Portfolio.objects.using(db_alias).values_list('id', flat=True):
        positions = {}
        touched_security_ids = set()
        trade_transactions = (
            TradeTransaction.objects
            .using(db_alias)
            .filter(portfolio_id=portfolio_id)
            .order_by('transaction_date', 'created_at', 'id')
        )

        for trade_transaction in trade_transactions:
            if trade_transaction.transaction_type not in {'BUY', 'SELL'}:
                trade_transaction.realized_profit_loss = ZERO
                trade_transaction.save(update_fields=['realized_profit_loss'])
                continue

            security_id = trade_transaction.security_id
            touched_security_ids.add(security_id)
            quantity = trade_transaction.quantity or ZERO
            price = trade_transaction.price or ZERO
            fee = trade_transaction.fee or ZERO
            gross_amount = quantity * price
            position = positions.get(security_id, {
                'quantity': ZERO,
                'average_cost': ZERO,
            })

            if trade_transaction.transaction_type == 'BUY':
                current_cost = position['quantity'] * position['average_cost']
                added_cost = gross_amount + fee
                next_quantity = position['quantity'] + quantity
                if next_quantity > ZERO:
                    positions[security_id] = {
                        'quantity': next_quantity,
                        'average_cost': quantize_average_cost(
                            (current_cost + added_cost) / next_quantity
                        ),
                    }
                trade_transaction.realized_profit_loss = ZERO

            if trade_transaction.transaction_type == 'SELL':
                realized_profit_loss = gross_amount - fee - (quantity * position['average_cost'])
                trade_transaction.realized_profit_loss = quantize_money(realized_profit_loss)
                next_quantity = position['quantity'] - quantity
                if next_quantity <= ZERO:
                    positions.pop(security_id, None)
                else:
                    positions[security_id] = {
                        'quantity': next_quantity,
                        'average_cost': position['average_cost'],
                    }

            trade_transaction.save(update_fields=['realized_profit_loss'])

        for security_id in touched_security_ids:
            position = positions.get(security_id)
            if position and position['quantity'] > ZERO:
                Holding.objects.using(db_alias).update_or_create(
                    portfolio_id=portfolio_id,
                    security_id=security_id,
                    defaults={
                        'quantity': position['quantity'],
                        'average_cost': position['average_cost'],
                    },
                )
            else:
                Holding.objects.using(db_alias).filter(
                    portfolio_id=portfolio_id,
                    security_id=security_id,
                ).delete()


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_portfolio_initial_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradetransaction',
            name='realized_profit_loss',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20),
        ),
        migrations.RunPython(backfill_realized_profit_loss, noop_reverse),
    ]
